/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;


import Classes.Course;
import DatabaseConnection.DataReader;
import Classes.Student;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Doriela
 */
public class MainUserWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainUserWindow
     */
    private Student user=Student.getCurrentUser();
    public MainUserWindow() {
        initComponents();
        
        //setExtendedState(JFrame.MAXIMIZED_BOTH);
        lblWelcome.setText("<html><p style='text-align:center;'>Welcome</p>"+"<p style='text-align:center'>"
                            +user.getName()+"  "+user.getSurname()+"!</p></html>");
        populateMyCourseTable();
        lblError.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jScrollPane2 = new javax.swing.JScrollPane();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel5 = new javax.swing.JLabel();
        lblWelcome = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnSearchCourses = new javax.swing.JButton();
        btnCheckCourseDetails = new javax.swing.JButton();
        btnUpdateProfile = new javax.swing.JButton();
        btnViewStudents = new javax.swing.JButton();
        btnSeeFriends = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUserCourses = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txtCourseID = new javax.swing.JTextField();
        btnGoToCourse = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnRefreshTable = new javax.swing.JButton();
        lblError = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main Window");
        setBackground(new java.awt.Color(204, 255, 204));

        jDesktopPane1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/insideIcon.jpg"))); // NOI18N

        lblWelcome.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(255, 255, 255));
        lblWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWelcome.setText("Welcome!");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/insideIcon.jpg"))); // NOI18N

        btnSearchCourses.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSearchCourses.setText("Search Available Courses");
        btnSearchCourses.setToolTipText("View your available courses and add/drop them");
        btnSearchCourses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchCoursesActionPerformed(evt);
            }
        });

        btnCheckCourseDetails.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCheckCourseDetails.setText("Check Course Details");
        btnCheckCourseDetails.setToolTipText("Check course details and participants");
        btnCheckCourseDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckCourseDetailsActionPerformed(evt);
            }
        });

        btnUpdateProfile.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUpdateProfile.setText("Update Profile");
        btnUpdateProfile.setToolTipText("Update name,surname and age");
        btnUpdateProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateProfileActionPerformed(evt);
            }
        });

        btnViewStudents.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnViewStudents.setText("See All Students");
        btnViewStudents.setToolTipText("View all students and add friends");
        btnViewStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewStudentsActionPerformed(evt);
            }
        });

        btnSeeFriends.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSeeFriends.setText("See My Friends");
        btnSeeFriends.setToolTipText("View friends and their course list");
        btnSeeFriends.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeeFriendsActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 34)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("My Course List");

        tblUserCourses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Course ID", "Title", "Instructor", "Day", "Time", "Location", "Credits", "Department", "Faculty", "Eligibility"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblUserCourses.setRowHeight(26);
        tblUserCourses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUserCoursesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblUserCourses);
        if (tblUserCourses.getColumnModel().getColumnCount() > 0) {
            tblUserCourses.getColumnModel().getColumn(0).setMinWidth(15);
            tblUserCourses.getColumnModel().getColumn(0).setPreferredWidth(15);
            tblUserCourses.getColumnModel().getColumn(1).setMinWidth(25);
            tblUserCourses.getColumnModel().getColumn(1).setPreferredWidth(25);
            tblUserCourses.getColumnModel().getColumn(2).setMinWidth(25);
            tblUserCourses.getColumnModel().getColumn(2).setPreferredWidth(25);
            tblUserCourses.getColumnModel().getColumn(3).setMinWidth(10);
            tblUserCourses.getColumnModel().getColumn(3).setPreferredWidth(10);
            tblUserCourses.getColumnModel().getColumn(4).setMinWidth(7);
            tblUserCourses.getColumnModel().getColumn(4).setPreferredWidth(7);
            tblUserCourses.getColumnModel().getColumn(5).setMinWidth(10);
            tblUserCourses.getColumnModel().getColumn(5).setPreferredWidth(10);
            tblUserCourses.getColumnModel().getColumn(6).setMinWidth(10);
            tblUserCourses.getColumnModel().getColumn(6).setPreferredWidth(10);
            tblUserCourses.getColumnModel().getColumn(7).setMinWidth(20);
            tblUserCourses.getColumnModel().getColumn(7).setPreferredWidth(20);
            tblUserCourses.getColumnModel().getColumn(8).setMinWidth(20);
            tblUserCourses.getColumnModel().getColumn(8).setPreferredWidth(20);
            tblUserCourses.getColumnModel().getColumn(9).setMinWidth(12);
            tblUserCourses.getColumnModel().getColumn(9).setPreferredWidth(12);
        }

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Enter Course ID:");

        txtCourseID.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        btnGoToCourse.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGoToCourse.setText("Go To Course Page");
        btnGoToCourse.setToolTipText("Go to Course");
        btnGoToCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoToCourseActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnExit.setText("Log Out");
        btnExit.setToolTipText("Log out");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnRefreshTable.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRefreshTable.setText("Refresh Table");
        btnRefreshTable.setToolTipText("Go to Course");
        btnRefreshTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshTableActionPerformed(evt);
            }
        });

        lblError.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblError.setForeground(new java.awt.Color(255, 255, 255));
        lblError.setText("Error!");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Please refresh the table after you add or drop a course");

        jDesktopPane1.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(lblWelcome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnSearchCourses, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnCheckCourseDetails, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnUpdateProfile, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnViewStudents, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnSeeFriends, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(txtCourseID, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnGoToCourse, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnExit, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnRefreshTable, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(lblError, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1042, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(btnSearchCourses)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCheckCourseDetails)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnViewStudents)
                                .addGap(18, 18, 18)
                                .addComponent(btnSeeFriends)
                                .addGap(18, 18, 18)
                                .addComponent(btnUpdateProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)
                                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRefreshTable)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(txtCourseID, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnGoToCourse))
                    .addComponent(lblError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(442, 442, 442))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel6))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jLabel5))
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(lblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 29, 29)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSearchCourses, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCheckCourseDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnViewStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSeeFriends, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUpdateProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRefreshTable, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCourseID, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGoToCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(213, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jDesktopPane1);

        jMenu1.setText("Help");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1128, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 669, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchCoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchCoursesActionPerformed
        // TODO add your handling code here:
        SearchCoursesWindow.main();
        
    }//GEN-LAST:event_btnSearchCoursesActionPerformed

    private void btnCheckCourseDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckCourseDetailsActionPerformed
        // TODO add your handling code here:
        CourseDetailsWindow.main();
    }//GEN-LAST:event_btnCheckCourseDetailsActionPerformed

    private void btnUpdateProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateProfileActionPerformed
        // TODO add your handling code here:
        UpdateProfileWindow.main();
    }//GEN-LAST:event_btnUpdateProfileActionPerformed

    private void btnViewStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewStudentsActionPerformed
        // TODO add your handling code here:
        SeeAllStudentsWindow.main();
    }//GEN-LAST:event_btnViewStudentsActionPerformed

    private void btnSeeFriendsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeeFriendsActionPerformed
        // TODO add your handling code here:
        FriendsListWindow.main();
    }//GEN-LAST:event_btnSeeFriendsActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(rootPane, "Are you sure about logging out?")==JOptionPane.YES_OPTION){
           System.exit(0);
        };
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnRefreshTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshTableActionPerformed
        // TODO add your handling code here:
        populateMyCourseTable();
    }//GEN-LAST:event_btnRefreshTableActionPerformed

    private void btnGoToCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoToCourseActionPerformed
        // TODO add your handling code here:
        String courseIDStr= txtCourseID.getText();
        try{
            int courseID= Integer.parseInt(courseIDStr);
            Course course= Course.getCourse(courseID);
            if(course!=null){
                user.getCourseList(user.getID());
                if(user.hasCourse(courseID)){
                    
                    CoursePageWindow.main(course);//open the course page
                }
                else{
                    //not in courses list
                    lblError.setText("This course is not in your course list!");
                    lblError.setVisible(true);
                }
            }
            else{
                //course does not exist
                lblError.setText("This course does not exist!");
                lblError.setVisible(true);
                
            }
        }
        catch(NumberFormatException e){
            //wrong id
            lblError.setText("Wrong ID! Must be numeric!");
            lblError.setVisible(true);
        }
        
    }//GEN-LAST:event_btnGoToCourseActionPerformed

    private void tblUserCoursesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUserCoursesMouseClicked
        // TODO add your handling code here:
        int index=tblUserCourses.getSelectedRow();
        TableModel model=tblUserCourses.getModel();
        int courseID=Integer.parseInt(model.getValueAt(index, 0).toString());//get the ID of the selected row
        txtCourseID.setText(new Integer (courseID).toString());
    }//GEN-LAST:event_tblUserCoursesMouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        HelpWindow.main();
    }//GEN-LAST:event_jMenu1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUserWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUserWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUserWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUserWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainUserWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheckCourseDetails;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnGoToCourse;
    private javax.swing.JButton btnRefreshTable;
    private javax.swing.JButton btnSearchCourses;
    private javax.swing.JButton btnSeeFriends;
    private javax.swing.JButton btnUpdateProfile;
    private javax.swing.JButton btnViewStudents;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JTable tblUserCourses;
    private javax.swing.JTextField txtCourseID;
    // End of variables declaration//GEN-END:variables

    public void populateMyCourseTable() {
        DefaultTableModel modelofThistable=(DefaultTableModel) tblUserCourses.getModel();
        modelofThistable.setRowCount(0);//clear all table contents
        Object[] rowInfo= new Object[10];
        ArrayList<Course> userCourseList= new ArrayList<>();
        userCourseList=user.getCourseList(user.getID());//here we have the courselist of the user
        
        //adding all the course of the current user tothe table
        for(Course thisCourse: userCourseList){
            
            rowInfo[0]=thisCourse.getID();
            rowInfo[1]=thisCourse.getTitle();
            rowInfo[2]=thisCourse.getInstructor();
            rowInfo[3]=thisCourse.getDay();
            rowInfo[4]=thisCourse.getTime();
            rowInfo[5]=thisCourse.getLocation();
            rowInfo[6]=thisCourse.getCredits();
            rowInfo[7]=thisCourse.getDepartment();
            rowInfo[8]=thisCourse.getFaculty();
            rowInfo[9]=thisCourse.getEligibility();
            modelofThistable.addRow(rowInfo);
            
        }
        
        tblUserCourses.setFillsViewportHeight(true);
    }
    
    
    public void refreshTable(){
       populateMyCourseTable();//refresh table
    }
    }

